name: OpenMRS Login Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb
        wget -N https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/linux64/chromedriver-linux64.zip ./drivers
        unzip ./drivers/chromedriver_linux64.zip -d ./drivers
        chmod +x ./drivers/chromedriver

    - name: Run tests
      run: |
        Xvfb :99 & export DISPLAY=:99
        pytest --html=reports/report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/report.html
